/** This file was autogenerated by Haiku at 20170814201344. */
/** Copyright (c) 2017 taylor2. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "205be184-9fa9-41a0-869f-bcf9a55e6e43",
    type: "haiku",
    name: "TestMicro",
    relpath: "code/main/code.js",
    core: "2.1.31",
    version: "0.0.4",
    organization: "taylor2",
    project: "TestMicro",
    branch: "master"
  },

  options: {},
  states: {},
  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:ae432053ba76": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 204, edited: true } },
        "sizeAbsolute.y": { "0": { value: 174, edited: true } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } }
      },
      "haiku:66417a4f4cfe": {
        viewBox: { "0": { value: "0 0 169 91" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 169 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 91 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 20, edited: true } },
        "translation.y": {
          "0": { value: 75, edited: true, curve: "easeInOutQuad" },
          "1717": { value: 5, edited: true, curve: "easeInOutQuad" },
          "3400": { value: 75, edited: true }
        },
        "style.zIndex": { "0": { value: 1 } }
      },
      "haiku:40a3bc2e308f": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:dd5e84b30460": {
        d: {
          "0": {
            value: "M9.03182718,2.49464752 C7.90290772,2.23852967 6.72195833,2.3451433 5.65716144,2.79930525 C2.86313107,3.99102764 1.5642038,7.22211865 2.75592619,10.016149 L17.6275588,44.8831565 L2.60495252,81.0195665 C2.16509794,82.0776229 2.06668345,83.2466388 2.32345428,84.3633412 C3.00413968,87.3236579 5.95575512,89.1716643 8.91607189,88.4909789 L82.9747901,71.4621633 L160.159444,88.6105871 C161.265744,88.8563782 162.420962,88.7544251 163.467113,88.3186709 C166.271155,87.1507002 167.597453,83.9307476 166.429482,81.1267054 L151.372446,44.9780557 L166.268529,9.98389766 C166.720165,8.92290659 166.826905,7.74680086 166.573659,6.62183703 C165.906554,3.65843045 162.963443,1.79691042 160.000036,2.46401566 L84.1549657,19.5378268 L9.03182718,2.49464752 Z"
          }
        },
        stroke: { "0": { value: "#293539" } },
        "stroke-width": { "0": { value: "3" } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: { "haiku-title": "TestMicro", "haiku-id": "ae432053ba76" },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/bow.sketch.contents/slices/Rect.svg",
          "haiku-title": "Rect",
          "haiku-id": "66417a4f4cfe"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "426481e92a02" },
            children: ["Rect"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "bd25a6738db2" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "b82da04d55f3" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "40a3bc2e308f" },
            children: [
              {
                elementName: "path",
                attributes: { id: "Rect", "haiku-id": "dd5e84b30460" },
                children: []
              }
            ]
          }
        ]
      }
    ]
  }
};
