/** This file was autogenerated by Haiku at 20170814145358. */
/** Copyright (c) 2017 Matthew. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "HAIKU_SHARE_UUID",
    type: "haiku",
    name: "UsersMatthewCodeHaikuTeamMonoPackagesHaikuPlumbingTestFixturesProjectsBlankProject",
    relpath: "code/main/code.js"
  },

  options: {},
  states: {},
  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:0e366ff49e89": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 272, edited: true } },
        "sizeAbsolute.y": { "0": { value: 218, edited: true } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } }
      },
      "haiku:42d44ee07131": {
        viewBox: { "0": { value: "0 0 46 50" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 112.5, edited: true } },
        "translation.y": { "0": { value: 70, edited: true } },
        "style.zIndex": { "0": { value: 1 } }
      },
      "haiku:f29e4f6cb2a5": {
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:8137e046d891": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:8946578eab34": {
        fill: { "0": { value: "#D8D8D8" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-8ecf01" } }
      },
      "haiku:2b45076c27fa": {
        stroke: { "0": { value: "#979797" } },
        "stroke-width": { "0": { value: "1" } },
        x: { "0": { value: "0.5" } },
        y: { "0": { value: "0.5" } },
        "sizeAbsolute.x": { "0": { value: 45 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 49 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:31258f8ab25f": {
        viewBox: { "0": { value: "0 0 46 50" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: -9.5, edited: true } },
        "translation.y": { "0": { value: -19, edited: true } },
        "style.zIndex": { "0": { value: 2 } },
        "rotation.z": { "0": { value: 0.2771715510708537, edited: true } }
      },
      "haiku:fb742fb69b77": {
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:594cdd60ae0b": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:f67b48b06e58": {
        fill: { "0": { value: "#D8D8D8" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-385c1b" } }
      },
      "haiku:c3eb19440628": {
        stroke: { "0": { value: "#979797" } },
        "stroke-width": { "0": { value: "1" } },
        x: { "0": { value: "0.5" } },
        y: { "0": { value: "0.5" } },
        "sizeAbsolute.x": { "0": { value: 45 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 49 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:22b7b1f60d74": {
        viewBox: { "0": { value: "0 0 46 50" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 265.5, edited: true } },
        "translation.y": { "0": { value: -11.999999999999977, edited: true } },
        "style.zIndex": { "0": { value: 3 } },
        "scale.y": { "0": { value: 1.7183255169324736, edited: true } },
        "scale.x": { "0": { value: 2.00953729030264, edited: true } },
        "rotation.z": { "0": { value: 0.12561027396713254, edited: true } }
      },
      "haiku:aaa4130d5a5c": {
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:e541fed2e2ab": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:a59e87674819": {
        fill: { "0": { value: "#D8D8D8" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-94bebf" } }
      },
      "haiku:4773a01c667c": {
        stroke: { "0": { value: "#979797" } },
        "stroke-width": { "0": { value: "1" } },
        x: { "0": { value: "0.5" } },
        y: { "0": { value: "0.5" } },
        "sizeAbsolute.x": { "0": { value: 45 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 49 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:af30bf440abb": {
        viewBox: { "0": { value: "0 0 46 50" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: -11.499999999999996, edited: true } },
        "translation.y": { "0": { value: 194, edited: true } },
        "style.zIndex": { "0": { value: 4 } },
        "rotation.z": { "0": { value: -0.1417907507882573, edited: true } },
        "scale.x": { "0": { value: 1.3996984616011476, edited: true } },
        "scale.y": { "0": { value: 1.2545193523513833, edited: true } }
      },
      "haiku:d65e40e92830": {
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:4e591a679750": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:fc862f116147": {
        fill: { "0": { value: "#D8D8D8" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-9c9908" } }
      },
      "haiku:f4b270827ce6": {
        stroke: { "0": { value: "#979797" } },
        "stroke-width": { "0": { value: "1" } },
        x: { "0": { value: "0.5" } },
        y: { "0": { value: "0.5" } },
        "sizeAbsolute.x": { "0": { value: 45 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 49 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:f069f33e83ff": {
        viewBox: { "0": { value: "0 0 46 50" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 239.5, edited: true } },
        "translation.y": { "0": { value: 184, edited: true } },
        "style.zIndex": { "0": { value: 5 } },
        "rotation.z": { "0": { value: 0.2188911395554799, edited: true } }
      },
      "haiku:cc0f826c25ec": {
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 46 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 50 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:2e5185300c7c": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:7d3dc0b702bc": {
        fill: { "0": { value: "#D8D8D8" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-ffb45e" } }
      },
      "haiku:ebdac56db0ba": {
        stroke: { "0": { value: "#979797" } },
        "stroke-width": { "0": { value: "1" } },
        x: { "0": { value: "0.5" } },
        y: { "0": { value: "0.5" } },
        "sizeAbsolute.x": { "0": { value: 45 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 49 } },
        "sizeMode.y": { "0": { value: 1 } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: {
      "haiku-title": "UsersMatthewCodeHaikuTeamMonoPackagesHaikuPlumbingTestFixturesProjectsBlankProject",
      "haiku-id": "0e366ff49e89"
    },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/micro.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "42d44ee07131"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "81a41f7d99c1" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "51179145a574" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "3060698286a1" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "path-1-8ecf01", "haiku-id": "f29e4f6cb2a5" },
                children: []
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "8137e046d891" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Rectangle", "haiku-id": "c4a9f655ef56" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "8946578eab34" },
                    children: []
                  },
                  {
                    elementName: "rect",
                    attributes: { "haiku-id": "2b45076c27fa" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/micro.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "31258f8ab25f"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "a02803bce05b" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "fc1b45a9d2d0" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "a7502fc6608e" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "path-1-385c1b", "haiku-id": "fb742fb69b77" },
                children: []
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "594cdd60ae0b" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Rectangle", "haiku-id": "1e8849ec0723" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "f67b48b06e58" },
                    children: []
                  },
                  {
                    elementName: "rect",
                    attributes: { "haiku-id": "c3eb19440628" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/micro.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "22b7b1f60d74"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "67b0a9386d71" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "47a02d6d53bc" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "779a35cbbc06" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "path-1-94bebf", "haiku-id": "aaa4130d5a5c" },
                children: []
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "e541fed2e2ab" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Rectangle", "haiku-id": "b8a45c54ad45" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "a59e87674819" },
                    children: []
                  },
                  {
                    elementName: "rect",
                    attributes: { "haiku-id": "4773a01c667c" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/micro.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "af30bf440abb"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "06370a8070de" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "ea62de515f1c" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "140a948b8bcb" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "path-1-9c9908", "haiku-id": "d65e40e92830" },
                children: []
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "4e591a679750" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Rectangle", "haiku-id": "80f466c689b8" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "fc862f116147" },
                    children: []
                  },
                  {
                    elementName: "rect",
                    attributes: { "haiku-id": "f4b270827ce6" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/micro.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "f069f33e83ff"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "12c5e577a801" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "ebe62cbe9a5c" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "b221f0996b2b" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "path-1-ffb45e", "haiku-id": "cc0f826c25ec" },
                children: []
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "2e5185300c7c" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Rectangle", "haiku-id": "631305fef722" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "7d3dc0b702bc" },
                    children: []
                  },
                  {
                    elementName: "rect",
                    attributes: { "haiku-id": "ebdac56db0ba" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
};
