/** This file was autogenerated by Haiku at 20170821074401. */
/** Copyright (c) 2017 taylor2. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "HAIKU_SHARE_UUID",
    type: "haiku",
    name: "holster",
    relpath: "code/main/code.js",
    player: "2.1.34",
    version: "0.0.32",
    organization: "taylor2",
    project: "holster",
    branch: "master"
  },

  options: {},
  states: {
    scale1: { type: "number", value: 0.5 },
    scale2: { type: "number", value: 0.9 },
    scale3: { type: "number", value: 1.3 },
    scale4: { type: "number", value: 1.1 },
    scale5: { type: "number", value: 1.3 },
    pos1: { type: "number", value: 5 },
    pos2: { type: "number", value: -10 },
    pos3: { type: "number", value: -30 },
    pos4: { type: "number", value: -80 },
    pos5: { type: "number", value: 0 },
    xOffset: { type: "number", value: 30 }
  },

  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:c93f54ae7170": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 870, edited: true } },
        "sizeAbsolute.y": { "0": { value: 420, edited: true } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } }
      },
      "haiku:24b695f287bc": {
        "controlFlow.placeholder": { "0": { value: 0 } },
        viewBox: { "0": { value: "0 0 232 163" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 232 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 163 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": {
          "0": { value: 74.5, edited: true },
          "183": { value: 74.5, edited: true, curve: "easeOutBack" },
          "817": {
            value: function({ $user, $user: { mouse, mouse: { x } } }) {
              return 78 + $user.mouse.x / 35;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 430, edited: true },
          "183": { value: 430, edited: true, curve: "easeOutBack" },
          "817": {
            value: function({ $user, $user: { mouse, mouse: { y } } }) {
              return 120 + $user.mouse.y / 35;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 7 } },
        opacity: {
          "0": { value: 0, edited: true },
          "17": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "483": { value: 1, edited: true }
        }
      },
      "haiku:67648e4f5863": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:4f19ff58c41e": {
        fill: { "0": { value: "#4AFEA9" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 232 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 163 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:f4995f31ac79": {
        viewBox: { "0": { value: "0 0 16 30" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } },
        "controlFlow.placeholder": { "0": { value: 1 } },
        "translation.x": {
          "0": { value: 0, edited: true },
          "183": {
            value: function(
              { xOffset, $user, $user: { mouse, mouse: { x } } }
            ) {
              return xOffset + $user.mouse.x / 20;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 500, edited: true },
          "183": {
            value: function({ $user, $user: { mouse, mouse: { y } }, pos1 }) {
              return 144 + $user.mouse.y / 20 + pos1;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 2 } },
        "scale.x": {
          "0": {
            value: function({ scale1 }) {
              return scale1;
            },
            edited: true
          }
        },
        "scale.y": {
          "0": {
            value: function({ scale1 }) {
              return scale1;
            },
            edited: true
          }
        },
        opacity: {
          "0": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "817": { value: 1, edited: true }
        }
      },
      "haiku:a77acdffd4a4": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:f212a359af1f": {
        fill: { "0": { value: "#DB4AFE" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:2445bb56c64b": {
        viewBox: { "0": { value: "0 0 16 30" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } },
        "controlFlow.placeholder": { "0": { value: 3 } },
        "translation.x": {
          "0": { value: 0, edited: true },
          "183": {
            value: function(
              { xOffset, $user, $user: { mouse, mouse: { x } } }
            ) {
              return xOffset + $user.mouse.x / 12 + 10;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 500, edited: true },
          "183": {
            value: function({ $user, $user: { mouse, mouse: { y } }, pos3 }) {
              return 144 + $user.mouse.y / 12 + pos3;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 5 } },
        "scale.x": {
          "0": {
            value: function({ scale2 }) {
              return scale2;
            },
            edited: true
          }
        },
        "scale.y": {
          "0": {
            value: function({ scale2 }) {
              return scale2;
            },
            edited: true
          }
        },
        opacity: {
          "0": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "600": { value: 1, edited: true }
        }
      },
      "haiku:f677e68544d1": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:b5f3d409b993": {
        fill: { "0": { value: "#DB4AFE" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:c180acd56de4": {
        viewBox: { "0": { value: "0 0 16 30" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } },
        "controlFlow.placeholder": { "0": { value: 4 } },
        "translation.x": {
          "0": { value: 0, edited: true },
          "183": {
            value: function(
              { xOffset, $user, $user: { mouse, mouse: { x } } }
            ) {
              return xOffset + $user.mouse.x / 10 + 230;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 500, edited: true },
          "183": {
            value: function({ $user, $user: { mouse, mouse: { y } }, pos1 }) {
              return 144 + $user.mouse.y / 10 + pos1;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 6 } },
        "scale.x": {
          "0": {
            value: function({ scale3 }) {
              return scale3;
            },
            edited: true
          }
        },
        "scale.y": {
          "0": {
            value: function({ scale3 }) {
              return scale3;
            },
            edited: true
          }
        },
        opacity: {
          "0": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "817": { value: 1, edited: true }
        }
      },
      "haiku:fede4e69bb6b": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:1ea0e24614c3": {
        fill: { "0": { value: "#DB4AFE" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:bc7b964e08e6": {
        viewBox: { "0": { value: "0 0 16 30" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } },
        "controlFlow.placeholder": { "0": { value: 2 } },
        "translation.x": {
          "0": { value: 0, edited: true },
          "183": {
            value: function(
              { xOffset, $user, $user: { mouse, mouse: { x } } }
            ) {
              return xOffset + $user.mouse.x / 19 + 230;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 500, edited: true },
          "183": {
            value: function({ $user, $user: { mouse, mouse: { y } } }) {
              return 144 + $user.mouse.y / 19 + 13;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 1 } },
        "scale.x": {
          "0": {
            value: function({ scale2 }) {
              return scale2;
            },
            edited: true
          }
        },
        "scale.y": {
          "0": {
            value: function({ scale2 }) {
              return scale2;
            },
            edited: true
          }
        },
        opacity: {
          "0": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "817": { value: 1, edited: true }
        }
      },
      "haiku:afedb3385a28": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:3262361f9f6a": {
        fill: { "0": { value: "#DB4AFE" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:b343a07fdc0a": {
        viewBox: { "0": { value: "0 0 16 30" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } },
        "controlFlow.placeholder": { "0": { value: 5 } },
        "translation.x": {
          "0": { value: 0, edited: true },
          "183": {
            value: function(
              { xOffset, $user, $user: { mouse, mouse: { x } } }
            ) {
              return xOffset + $user.mouse.x / 19 + 200;
            },
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 500, edited: true },
          "183": {
            value: function({ $user, $user: { mouse, mouse: { y } }, pos5 }) {
              return 144 + $user.mouse.y / 12 + pos5;
            },
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 3 } },
        "scale.x": {
          "0": {
            value: function({ scale5 }) {
              return scale5;
            },
            edited: true
          }
        },
        "scale.y": {
          "0": {
            value: function({ scale5 }) {
              return scale5;
            },
            edited: true
          }
        },
        opacity: {
          "0": { value: 0, edited: true },
          "183": { value: 0, edited: true, curve: "linear" },
          "817": { value: 1, edited: true }
        }
      },
      "haiku:fdd0fb35ee36": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:e6e9eb1e9fb6": {
        fill: { "0": { value: "#DB4AFE" } },
        x: { "0": { value: "0" } },
        y: { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 16 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 30 } },
        "sizeMode.y": { "0": { value: 1 } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: { "haiku-title": "holster", "haiku-id": "c93f54ae7170" },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/Rectangle.svg",
          "haiku-title": "Rectangle",
          "haiku-id": "24b695f287bc"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "bae44a3d7d26" },
            children: ["Rectangle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "fa97f32a6032" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "0310079b31df" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "67648e4f5863" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "Rectangle", "haiku-id": "4f19ff58c41e" },
                children: []
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/particle.svg",
          "haiku-title": "particle",
          "haiku-id": "f4995f31ac79"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "d6a956c46e96" },
            children: ["particle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "e4aec98dd773" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "6a219b542345" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "a77acdffd4a4" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "particle", "haiku-id": "f212a359af1f" },
                children: []
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/particle.svg",
          "haiku-title": "particle",
          "haiku-id": "2445bb56c64b"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "d2bb1d0ca186" },
            children: ["particle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "229ffe6b8f80" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "ba218062037c" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "f677e68544d1" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "particle", "haiku-id": "b5f3d409b993" },
                children: []
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/particle.svg",
          "haiku-title": "particle",
          "haiku-id": "c180acd56de4"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "f6082ac34e0a" },
            children: ["particle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "a71336b3598d" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "7a4353860042" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "fede4e69bb6b" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "particle", "haiku-id": "1ea0e24614c3" },
                children: []
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/particle.svg",
          "haiku-title": "particle",
          "haiku-id": "bc7b964e08e6"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "3328bbc9ef7c" },
            children: ["particle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "c6cc57161f98" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "6af55fa37b31" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "afedb3385a28" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "particle", "haiku-id": "3262361f9f6a" },
                children: []
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/particle.svg",
          "haiku-title": "particle",
          "haiku-id": "b343a07fdc0a"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "0be91d459b06" },
            children: ["particle"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "416fd806d01f" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "d5354f166d3a" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "fdd0fb35ee36" },
            children: [
              {
                elementName: "rect",
                attributes: { id: "particle", "haiku-id": "e6e9eb1e9fb6" },
                children: []
              }
            ]
          }
        ]
      }
    ]
  }
};
