module.exports = {
  changeKeyframeValue: require('./changeKeyframeValue'),
  changePlaybackSpeed: require('./changePlaybackSpeed'),
  changeSegmentCurve: require('./changeSegmentCurve'),
  componentIdToSelector: require('./componentIdToSelector'),
  createKeyframe: require('./createKeyframe'),
  createTimeline: require('./createTimeline'),
  deleteEventHandler: require('./deleteEventHandler'),
  deleteKeyframe: require('./deleteKeyframe'),
  deleteStateValue: require('./deleteStateValue'),
  deleteTimeline: require('./deleteTimeline'),
  duplicateTimeline: require('./duplicateTimeline'),
  ensureTimeline: require('./ensureTimeline'),
  ensureTimelineGroup: require('./ensureTimelineGroup'),
  ensureTimelineProperty: require('./ensureTimelineProperty'),
  getSortedKeyframeKeys: require('./getSortedKeyframeKeys'),
  joinKeyframes: require('./joinKeyframes'),
  moveKeyframes: require('./moveKeyframes'),
  readAllEventHandlers: require('./readAllEventHandlers'),
  readAllStateValues: require('./readAllStateValues'),
  renameTimeline: require('./renameTimeline'),
  splitSegment: require('./splitSegment'),
  upsertEventHandler: require('./upsertEventHandler'),
  batchUpsertEventHandlers: require('./batchUpsertEventHandlers'),
  upsertStateValue: require('./upsertStateValue')
}
