var Haiku = require('@haiku/core')
/** This file was autogenerated by Haiku at 20170814183940. */
/** Copyright (c) 2017 taylor2. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "8960d836-362f-4cfe-a28b-d97d59b2427e",
    type: "haiku",
    name: "TestForce",
    relpath: "code/main/code.js",
    core: "2.1.31",
    version: "0.0.6",
    organization: "taylor2",
    project: "TestForce",
    branch: "master"
  },

  options: {},
  states: {},
  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:90e954f20b49": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 900, edited: true } },
        "sizeAbsolute.y": { "0": { value: 430, edited: true } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } },
        backgroundColor: { "0": { value: "red", edited: true } }
      },
      "haiku:0554341358c2": {
        viewBox: { "0": { value: "0 0 177 95" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 177 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 95 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": {
          "0": { value: 600, edited: true, curve: "easeOutBack" },
          "617": {
            value: Haiku.inject(function($user) {
              return 450 + $user.mouse.x / 5;
            }, '$user'),
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 600, edited: true, curve: "easeOutBack" },
          "617": {
            value: Haiku.inject(function($user) {
              return 220 + $user.mouse.y / 100;
            }, '$user'),
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 1 } },
        "rotation.z": { "0": { value: 0, edited: true } }
      },
      "haiku:c4bb950d1562": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:4fc51f9bf39c": {
        stroke: { "0": { value: "#293539" } },
        "stroke-width": { "0": { value: "3" } },
        "translation.x": { "0": { value: -299 } },
        "translation.y": { "0": { value: -131 } }
      },
      "haiku:df8cba73012e": {
        x: { "0": { value: "300.5" } },
        y: { "0": { value: "132.5" } },
        rx: { "0": { value: "7" } },
        "sizeAbsolute.x": { "0": { value: 174 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 92 } },
        "sizeMode.y": { "0": { value: 1 } }
      },
      "haiku:c6e66efd8f2d": {
        viewBox: { "0": { value: "0 0 177 95" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 177 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 95 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": {
          "0": { value: 600, edited: true, curve: "easeOutBack" },
          "350": {
            value: Haiku.inject(function($user) {
              return 450 + $user.mouse.x / 20;
            }, '$user'),
            edited: true
          }
        },
        "translation.y": {
          "0": { value: 600, edited: true, curve: "easeOutBack" },
          "350": {
            value: Haiku.inject(function($user) {
              return 220 + $user.mouse.y / 20;
            }, '$user'),
            edited: true
          }
        },
        "style.zIndex": { "0": { value: 1 } },
        "rotation.z": { "0": { value: 0, edited: true } },
        "controlFlow.placeholder": { "0": { value: 0, edited: true } }
      },
      "haiku:f41605155ad3": {},
      "haiku:637b9019ba82": {},
      "haiku:17b2bbf2f88c": {},
      "haiku:7c7e7efa8b74": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:0292ab9e52a8": {
        stroke: { "0": { value: "#293539" } },
        "stroke-width": { "0": { value: "3" } },
        "translation.x": { "0": { value: -299 } },
        "translation.y": { "0": { value: -131 } }
      },
      "haiku:dfe7fe93e5f0": {
        x: { "0": { value: "300.5" } },
        y: { "0": { value: "132.5" } },
        rx: { "0": { value: "7" } },
        "sizeAbsolute.x": { "0": { value: 174 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 92 } },
        "sizeMode.y": { "0": { value: 1 } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: { "haiku-title": "TestForce", "haiku-id": "90e954f20b49" },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/testforce.sketch.contents/slices/Rect.svg",
          "haiku-title": "Rect",
          "haiku-id": "0554341358c2"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "3916147f1da4" },
            children: ["Rect"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "e599b9fcf59a" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "75ed2df2694d" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "c4bb950d1562" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Artboard", "haiku-id": "4fc51f9bf39c" },
                children: [
                  {
                    elementName: "rect",
                    attributes: { id: "Rect", "haiku-id": "df8cba73012e" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/testforce.sketch.contents/slices/Rect.svg",
          "haiku-title": "Rect",
          "haiku-id": "c6e66efd8f2d"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "f41605155ad3" },
            children: ["Rect"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "637b9019ba82" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "17b2bbf2f88c" },
            children: []
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "7c7e7efa8b74" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Artboard", "haiku-id": "0292ab9e52a8" },
                children: [
                  {
                    elementName: "rect",
                    attributes: { id: "Rect", "haiku-id": "dfe7fe93e5f0" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
};
