declare let isTextNode: any;
declare let isIE: any;
declare let isEdge: any;
declare let getWindowsBrowserVersion: any;
declare let isMobile: any;
declare let applyCssLayout: any;
declare let scopeOfElement: any;
declare let hasPreserve3d: any;
declare let DEFAULT_PIXEL_RATIO: number;
declare let SVG: string;
declare let safeWindow: Window;
declare let PLATFORM_INFO: {
    hasWindow: boolean;
    isMobile: any;
    isIE: any;
    isEdge: any;
    windowsBrowserVersion: any;
    hasPreserve3d: any;
    devicePixelRatio: number;
};
declare let SVG_RENDERABLES: {
    a: boolean;
    audio: boolean;
    canvas: boolean;
    circle: boolean;
    ellipse: boolean;
    filter: boolean;
    foreignObject: boolean;
    g: boolean;
    iframe: boolean;
    image: boolean;
    line: boolean;
    mesh: boolean;
    path: boolean;
    polygon: boolean;
    polyline: boolean;
    rect: boolean;
    svg: boolean;
    switch: boolean;
    symbol: boolean;
    text: boolean;
    textPath: boolean;
    tspan: boolean;
    unknown: boolean;
    use: boolean;
    video: boolean;
};
declare function applyLayout(domElement: any, virtualElement: any, parentDomNode: any, parentVirtualElement: any, component: any, isPatchOperation: any, isKeyDifferent: any): any;
declare let warnings: {};
