import * as fse from 'fs-extra';
// @ts-ignore
import * as logger from 'haiku-serialization/src/utils/LoggerInstance';
import path = require('path');
import {ExporterInterface} from '..';
import BaseExporter from '../BaseExporter';
import {createBundle} from './createBundle';

import {
  getCopyrightNotice,
  getCurrentHumanTimestamp,
  getOrganizationNameOrFallback,
  getStandaloneName,
} from '@haiku/sdk-client/lib/ProjectDefinitions';

export enum BundleFormat {
  StandaloneFormat = 'StandaloneFormat',
  EmbedFormat = 'EmbedFormat',
}

export class StandaloneBundlerExporter extends BaseExporter implements ExporterInterface {

  generateStandAloneBundle (): Promise<string> {
    const projOrganizationName = this.bytecode.metadata.organization;
    const projName = this.bytecode.metadata.project;
    const projPath = this.bytecode.metadata.folder;

    const organizationName = getOrganizationNameOrFallback(projOrganizationName);
    const standaloneName = getStandaloneName(organizationName, projName);

    const autoGeneratedNotice = `This file was autogenerated by Haiku at ${getCurrentHumanTimestamp()}.`;
    const copyrightNotice = getCopyrightNotice(organizationName);

    logger.info('[project folder] bundling code/main/dom-embed.js');

    return new Promise<string>((resolve, reject) => {
      createBundle(
        path.join(projPath, 'code/main'),
        path.join(projPath, 'code/main/dom-standalone.js'),
        standaloneName,
        (bundleErr: any, bundledContents: any) => {
          if (bundleErr) {
            return reject(bundleErr);
          }
          logger.info('[project folder] bundling succeeded for', standaloneName);
          const finalContent = `/** ${autoGeneratedNotice}\n${copyrightNotice}\n*/\n${bundledContents}`;
          return resolve(finalContent);
        },
      );
    });
  }

  writeToFile (filename: string, framerate: number): Promise<void> {
    return this.generateStandAloneBundle().then((content) => {
      return fse.writeFile(filename, content);
    }).catch((error) => {
      logger.error(`[formats] caught exception during bundled StandaloneBundlerExporter: ${error.toString()}`);
      return fse.writeFile(filename, '{}');
    });
  }
}
