/** This file was autogenerated by Haiku at 20170814200036. */
var React = require('react') // Installed as a peer dependency of '@haiku/core'
var ReactDOM = require('react-dom') // Installed as a peer dependency of '@haiku/core'
var HaikuReactAdapter = require('@haiku/core/dom/react')
var React_TestForce = HaikuReactAdapter(require('./dom'))
var React_TestMicro = require('./micro/react-dom')
if (React_TestForce.default) React_TestForce = React_TestForce.default
React_TestForce.mount = function (element, React, ReactDOM) {
  class Main extends React.Component {
    render() {
      return React.createElement(React_TestForce, { key: 'force', name: 'force' },
        React.createElement(React_TestMicro, { key: 'micro', name: 'micro' })
      )
    }
  }
  ReactDOM.render(React.createElement(Main), element)
}
module.exports = React_TestForce
