var tape = require('tape')
var async = require('async')
var fse = require('haiku-fs-extra')
var cp = require('child_process')
var path = require('path')
var TestHelpers = require('./../TestHelpers')
tape('plumbing.00.authenticateUser', (t) => {
  t.plan(8)
  TestHelpers.launch((plumbing, teardown) => {
    return plumbing.authenticateUser('matthew+matthew@haiku.ai', 'supersecure', (err, resp) => {
      t.error(err, 'no auth err')
      t.ok(resp.username, 'username present')
      t.ok(resp.authToken, 'auth token present')
      t.ok(resp.organizationName, 'org name present')
      t.ok(plumbing.get('organizationName'), 'state org name present')
      t.ok(plumbing.get('username'), 'state username present')
      t.ok(plumbing.get('password'), 'state password present')
      t.ok(plumbing.get('inkstoneAuthToken'), 'state auth token present')
      teardown()
    })
  })
})
