const DOM_CLUSTERED_PROPS = {
  'mount.x': 'mount',
  'mount.y': 'mount',
  'mount.z': 'mount',
  'align.x': 'align',
  'align.y': 'align',
  'align.z': 'align',
  'origin.x': 'origin',
  'origin.y': 'origin',
  'origin.z': 'origin',
  'translation.x': 'translation',
  'translation.y': 'translation',
  'translation.z': 'translation', // This doesn't work for some reason, so leaving it out
  'rotation.x': 'rotation',
  'rotation.y': 'rotation',
  'rotation.z': 'rotation',
  // 'rotation.w': 'rotation', // Probably easiest not to let the user have control over quaternion math
  'scale.x': 'scale',
  'scale.y': 'scale',
  'scale.z': 'scale',
  'sizeMode.x': 'sizeMode',
  'sizeMode.y': 'sizeMode',
  'sizeMode.z': 'sizeMode',
  'sizeProportional.x': 'sizeProportional',
  'sizeProportional.y': 'sizeProportional',
  'sizeProportional.z': 'sizeProportional',
  'sizeDifferential.x': 'sizeDifferential',
  'sizeDifferential.y': 'sizeDifferential',
  'sizeDifferential.z': 'sizeDifferential',
  'sizeAbsolute.x': 'sizeAbsolute',
  'sizeAbsolute.y': 'sizeAbsolute',
  'sizeAbsolute.z': 'sizeAbsolute',
  'style.overflowX': 'overflow',
  'style.overflowY': 'overflow',
  '<rect>.x': '<rect>.offset',
  '<rect>.y': '<rect>.offset',
  '<rect>.width': '<rect>.size',
  '<rect>.height': '<rect>.size',
  '<rect>.rx': '<rect>.cornerRadius',
  '<rect>.ry': '<rect>.cornerRadius',
  '<circle>.cx': '<circle>.center',
  '<circle>.cy': '<circle>.center',
  '<ellipse>.cx': '<ellipse>.center',
  '<ellipse>.cy': '<ellipse>.center',
  '<ellipse>.rx': '<ellipse>.radius',
  '<ellipse>.ry': '<ellipse>.radius',
  '<line>.x1': '<line>.endpoints',
  '<line>.y1': '<line>.endpoints',
  '<line>.x2': '<line>.endpoints',
  '<line>.y2': '<line>.endpoints'
}

module.exports = DOM_CLUSTERED_PROPS
