/** This file was autogenerated by Haiku at 20170806192854. */
/** Copyright (c) 2017 taylor2. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "HAIKU_SHARE_UUID",
    type: "haiku",
    name: "UsersMatthewCodeHaikuTeamMonoPackagesHaikuPlumbingTestFixturesProjectsBlankProject",
    relpath: "code/main/code.js"
  },

  options: {},
  states: {
    filt: {
      value: 2
    }
  },
  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:0e366ff49e89": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 302, edited: true } },
        "sizeAbsolute.y": { "0": { value: 186, edited: true } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } }
      },
      "haiku:9cf4b34a6ea8": {
        viewBox: { "0": { value: "0 0 256 181" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 256 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 181 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 24, edited: true } },
        "translation.y": { "0": { value: 6.500000000000014, edited: true } },
        "style.zIndex": { "0": { value: 1 } },
        "scale.y": { "0": { value: 1.1767955801104972, edited: true } },
        "scale.x": { "0": { value: 1.25390625, edited: true } }
      },
      "haiku:175dad773a77": {
        x: { "0": { value: function({ filt }) {
          return filt + "0.0%"
        } } },
        y: { "0": { value: function({ filt }) {
          return filt + "0.0%"
        } } },
        filterUnits: { "0": { value: "objectBoundingBox" } },
        "sizeProportional.x": { "0": { value: 1.6 } },
        "sizeMode.x": { "0": { value: 0 } },
        "sizeProportional.y": { "0": { value: 1.6 } },
        "sizeMode.y": { "0": { value: 0 } }
      },
      "haiku:80ff99baee8b": {
        stdDeviation: { "0": { value: "10" } },
        in: { "0": { value: "SourceGraphic" } }
      },
      "haiku:9b285cbd0517": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:2e7c8978b254": {
        "fill-rule": { "0": { value: "nonzero" } },
        fill: { "0": { value: "#008000" } },
        "translation.x": { "0": { value: 16 } },
        "translation.y": { "0": { value: 36 } }
      },
      "haiku:d161efce30ec": {
        cx: { "0": { value: "50" } },
        cy: { "0": { value: "50" } },
        r: { "0": { value: "50" } }
      },
      "haiku:40f8f7cf3b03": {
        filter: { "0": { value: "url(#filter-1-8ecf01)" } },
        cx: { "0": { value: "160" } },
        cy: { "0": { value: "50" } },
        r: { "0": { value: "50" } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: {
      "haiku-title": "UsersMatthewCodeHaikuTeamMonoPackagesHaikuPlumbingTestFixturesProjectsBlankProject",
      "haiku-id": "0e366ff49e89"
    },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/filt.sketch.contents/slices/Slice.svg",
          "haiku-title": "Slice",
          "haiku-id": "9cf4b34a6ea8"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "21cfeded937a" },
            children: ["Slice"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "c80eb6c9a359" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "52072b71c66e" },
            children: [
              {
                elementName: "filter",
                attributes: {
                  id: "filter-1-8ecf01",
                  "haiku-id": "175dad773a77",
                  "sizeMode.x": 0,
                  "sizeMode.y": 0
                },
                children: [
                  {
                    elementName: "feGaussianBlur",
                    attributes: { "haiku-id": "80ff99baee8b" },
                    children: []
                  }
                ]
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "9b285cbd0517" },
            children: [
              {
                elementName: "g",
                attributes: { id: "filt", "haiku-id": "2e7c8978b254" },
                children: [
                  {
                    elementName: "circle",
                    attributes: { id: "Oval", "haiku-id": "d161efce30ec" },
                    children: []
                  },
                  {
                    elementName: "circle",
                    attributes: { id: "Oval", "haiku-id": "40f8f7cf3b03" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
};
