"use strict";
exports.__esModule = true;
var has_1 = require("./has");
var TEXT_CONTENT_SCHEMA = {
    content: 'string'
};
var LAYOUT_3D_SCHEMA = {
    shown: 'boolean',
    opacity: 'number',
    'mount.x': 'number',
    'mount.y': 'number',
    'mount.z': 'number',
    'align.x': 'number',
    'align.y': 'number',
    'align.z': 'number',
    'origin.x': 'number',
    'origin.y': 'number',
    'origin.z': 'number',
    'translation.x': 'number',
    'translation.y': 'number',
    'translation.z': 'number',
    'rotation.x': 'number',
    'rotation.y': 'number',
    'rotation.z': 'number',
    'rotation.w': 'number',
    'scale.x': 'number',
    'scale.y': 'number',
    'scale.z': 'number',
    'sizeAbsolute.x': 'number',
    'sizeAbsolute.y': 'number',
    'sizeAbsolute.z': 'number',
    'sizeProportional.x': 'number',
    'sizeProportional.y': 'number',
    'sizeProportional.z': 'number',
    'sizeDifferential.x': 'number',
    'sizeDifferential.y': 'number',
    'sizeDifferential.z': 'number',
    'sizeMode.x': 'number',
    'sizeMode.y': 'number',
    'sizeMode.z': 'number'
};
var LAYOUT_2D_SCHEMA = {
    shown: 'boolean',
    opacity: 'number',
    'mount.x': 'number',
    'mount.y': 'number',
    'align.x': 'number',
    'align.y': 'number',
    'origin.x': 'number',
    'origin.y': 'number',
    'translation.x': 'number',
    'translation.y': 'number',
    'translation.z': 'number',
    'rotation.x': 'number',
    'rotation.y': 'number',
    'rotation.z': 'number',
    'scale.x': 'number',
    'scale.y': 'number',
    'sizeAbsolute.x': 'number',
    'sizeAbsolute.y': 'number',
    'sizeProportional.x': 'number',
    'sizeProportional.y': 'number',
    'sizeDifferential.x': 'number',
    'sizeDifferential.y': 'number',
    'sizeMode.x': 'number',
    'sizeMode.y': 'number'
};
var PRESENTATION_SCHEMA = {
    alignmentBaseline: 'string',
    baselineShift: 'string',
    clipPath: 'string',
    clipRule: 'string',
    clip: 'string',
    colorInterpolationFilters: 'string',
    colorInterpolation: 'string',
    colorProfile: 'string',
    colorRendering: 'string',
    color: 'string',
    cursor: 'string',
    direction: 'string',
    display: 'string',
    dominantBaseline: 'string',
    enableBackground: 'string',
    fillOpacity: 'string',
    fillRule: 'string',
    fill: 'string',
    filter: 'string',
    floodColor: 'string',
    floodOpacity: 'string',
    fontFamily: 'string',
    fontSizeAdjust: 'string',
    fontSize: 'string',
    fontStretch: 'string',
    fontStyle: 'string',
    fontVariant: 'string',
    fontWeight: 'string',
    glyphOrientationHorizontal: 'string',
    glyphOrientationVertical: 'string',
    imageRendering: 'string',
    kerning: 'string',
    letterSpacing: 'string',
    lightingColor: 'string',
    markerEnd: 'string',
    markerMid: 'string',
    markerStart: 'string',
    mask: 'string',
    overflow: 'string',
    overflowX: 'string',
    overflowY: 'string',
    pointerEvents: 'string',
    shapeRendering: 'string',
    stopColor: 'string',
    stopOpacity: 'string',
    strokeDasharray: 'string',
    strokeDashoffset: 'string',
    strokeLinecap: 'string',
    strokeLinejoin: 'string',
    strokeMiterlimit: 'string',
    strokeOpacity: 'string',
    strokeWidth: 'string',
    stroke: 'string',
    textAnchor: 'string',
    textDecoration: 'string',
    textRendering: 'string',
    unicodeBidi: 'string',
    visibility: 'string',
    wordSpacing: 'string',
    writingMode: 'string'
};
var FILTER_SCHEMA = {
    x: 'string',
    y: 'string',
    width: 'string',
    height: 'string',
    filterRes: 'string',
    filterUnits: 'string',
    primitiveUnits: 'string'
};
var RECT_SCHEMA = {
    x: 'number',
    y: 'number',
    width: 'number',
    height: 'number',
    rx: 'number',
    ry: 'number'
};
var CIRCLE_SCHEMA = {
    r: 'number',
    cx: 'number',
    cy: 'number'
};
var ELLIPSE_SCHEMA = {
    rx: 'number',
    ry: 'number',
    cx: 'number',
    cy: 'number'
};
var LINE_SCHEMA = {
    x1: 'number',
    y1: 'number',
    x2: 'number',
    y2: 'number'
};
var POLYLINE_SCHEMA = {
    points: 'string'
};
var POLYGON_SCHEMA = {
    points: 'string'
};
var PATH_SCHEMA = {
    d: 'string'
};
var STYLE_SCHEMA = {
    'style.alignmentBaseline': 'string',
    'style.background': 'string',
    'style.backgroundAttachment': 'string',
    'style.backgroundColor': 'string',
    'style.backgroundImage': 'string',
    'style.backgroundPosition': 'string',
    'style.backgroundRepeat': 'string',
    'style.baselineShift': 'string',
    'style.border': 'string',
    'style.borderBottom': 'string',
    'style.borderBottomColor': 'string',
    'style.borderBottomStyle': 'string',
    'style.borderBottomWidth': 'string',
    'style.borderColor': 'string',
    'style.borderLeft': 'string',
    'style.borderLeftColor': 'string',
    'style.borderLeftStyle': 'string',
    'style.borderLeftWidth': 'string',
    'style.borderRight': 'string',
    'style.borderRightColor': 'string',
    'style.borderRightStyle': 'string',
    'style.borderRightWidth': 'string',
    'style.borderStyle': 'string',
    'style.borderTop': 'string',
    'style.borderTopColor': 'string',
    'style.borderTopStyle': 'string',
    'style.borderTopWidth': 'string',
    'style.borderWidth': 'string',
    'style.clear': 'string',
    'style.clip': 'string',
    'style.clipPath': 'string',
    'style.clipRule': 'string',
    'style.color': 'string',
    'style.colorInterpolation': 'string',
    'style.colorInterpolationFilters': 'string',
    'style.colorProfile': 'string',
    'style.colorRendering': 'string',
    'style.cssFloat': 'string',
    'style.cursor': 'string',
    'style.direction': 'string',
    'style.display': 'string',
    'style.dominantBaseline': 'string',
    'style.enableBackground': 'string',
    'style.fill': 'string',
    'style.fillOpacity': 'string',
    'style.fillRule': 'string',
    'style.filter': 'string',
    'style.floodColor': 'string',
    'style.floodOpacity': 'string',
    'style.font': 'string',
    'style.fontFamily': 'string',
    'style.fontSize': 'string',
    'style.fontSizeAdjust': 'string',
    'style.fontStretch': 'string',
    'style.fontStyle': 'string',
    'style.fontVariant': 'string',
    'style.fontWeight': 'string',
    'style.glyphOrientationHorizontal': 'string',
    'style.glyphOrientationVertical': 'string',
    'style.height': 'string',
    'style.imageRendering': 'string',
    'style.kerning': 'string',
    'style.left': 'string',
    'style.letterSpacing': 'string',
    'style.lightingColor': 'string',
    'style.lineHeight': 'string',
    'style.listStyle': 'string',
    'style.listStyleImage': 'string',
    'style.listStylePosition': 'string',
    'style.listStyleType': 'string',
    'style.margin': 'string',
    'style.marginBottom': 'string',
    'style.marginLeft': 'string',
    'style.marginRight': 'string',
    'style.marginTop': 'string',
    'style.markerEnd': 'string',
    'style.markerMid': 'string',
    'style.markerStart': 'string',
    'style.mask': 'string',
    'style.opacity': 'string',
    'style.overflow': 'string',
    'style.overflowX': 'string',
    'style.overflowY': 'string',
    'style.padding': 'string',
    'style.paddingBottom': 'string',
    'style.paddingLeft': 'string',
    'style.paddingRight': 'string',
    'style.paddingTop': 'string',
    'style.pageBreakAfter': 'string',
    'style.pageBreakBefore': 'string',
    'style.pointerEvents': 'string',
    'style.position': 'string',
    'style.shapeRendering': 'string',
    'style.stopColor': 'string',
    'style.stopOpacity': 'string',
    'style.stroke': 'string',
    'style.strokeDasharray': 'string',
    'style.strokeDashoffset': 'string',
    'style.strokeLinecap': 'string',
    'style.strokeLinejoin': 'string',
    'style.strokeMiterlimit': 'string',
    'style.strokeOpacity': 'string',
    'style.strokeWidth': 'string',
    'style.textAlign': 'string',
    'style.textAnchor': 'string',
    'style.textDecoration': 'string',
    'style.textDecorationBlink': 'string',
    'style.textDecorationLineThrough': 'string',
    'style.textDecorationNone': 'string',
    'style.textDecorationOverline': 'string',
    'style.textDecorationUnderline': 'string',
    'style.textIndent': 'string',
    'style.textRendering': 'string',
    'style.textTransform': 'string',
    'style.top': 'string',
    'style.unicodeBidi': 'string',
    'style.verticalAlign': 'string',
    'style.visibility': 'string',
    'style.width': 'string',
    'style.wordSpacing': 'string',
    'style.writingMode': 'string',
    'style.zIndex': 'number',
    'style.WebkitTapHighlightColor': 'string'
};
var HTML_STYLE_SHORTHAND_SCHEMA = {
    backgroundColor: 'string'
};
var CONTROL_FLOW_SCHEMA = {
    'controlFlow.repeat': 'any',
    'controlFlow.placeholder': 'any'
};
exports["default"] = {
    'missing-glyph': has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    a: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA, STYLE_SCHEMA),
    abbr: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    acronym: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    address: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    altGlyph: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    altGlyphDef: has_1["default"](),
    altGlyphItem: has_1["default"](),
    animate: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    animateColor: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    animateMotion: has_1["default"](),
    animateTransform: has_1["default"](),
    applet: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    area: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    article: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    aside: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    audio: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    b: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    base: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    basefont: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    bdi: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    bdo: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    big: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    blockquote: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    body: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    br: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    button: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    canvas: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    caption: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    center: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    circle: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, CIRCLE_SCHEMA),
    cite: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    clipPath: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    code: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    col: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    colgroup: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    'color-profile': has_1["default"](),
    command: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    cursor: has_1["default"](),
    datalist: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    dd: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    defs: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    del: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    desc: has_1["default"](),
    details: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    dfn: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    dir: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    discard: has_1["default"](),
    div: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    dl: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    dt: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    ellipse: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA, ELLIPSE_SCHEMA),
    em: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    embed: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    feBlend: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feColorMatrix: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feComponentTransfer: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feComposite: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feConvolveMatrix: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feDiffuseLighting: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feDisplacementMap: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feDistantLight: has_1["default"](),
    feDropShadow: has_1["default"](),
    feFlood: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feFuncA: has_1["default"](),
    feFuncB: has_1["default"](),
    feFuncG: has_1["default"](),
    feFuncR: has_1["default"](),
    feGaussianBlur: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feImage: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feMerge: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feMergeNode: has_1["default"](),
    feMorphology: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feOffset: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    fePointLight: has_1["default"](),
    feSpecularLighting: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feTile: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    feTurbulence: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    fieldset: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    figcaption: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    figure: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    filter: has_1["default"](LAYOUT_3D_SCHEMA, FILTER_SCHEMA),
    'font-face': has_1["default"](),
    'font-face-format': has_1["default"](),
    'font-face-name': has_1["default"](),
    'font-face-src': has_1["default"](),
    'font-face-uri': has_1["default"](),
    font: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA, STYLE_SCHEMA),
    footer: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    foreignObject: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    form: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    frame: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    frameset: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    g: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    glyph: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    glyphRef: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    h1: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    h2: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    h3: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    h4: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    h5: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    h6: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    hatch: has_1["default"](),
    hatchpath: has_1["default"](),
    head: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    header: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    hgroup: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    hkern: has_1["default"](),
    hr: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    html: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    i: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    iframe: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    image: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    img: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    input: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    ins: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    kbd: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    keygen: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    label: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    legend: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    li: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    line: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, LINE_SCHEMA),
    linearGradient: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    link: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    map: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    mark: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    marker: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    mask: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    menu: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    mesh: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA),
    meshgradient: has_1["default"](),
    meshpatch: has_1["default"](),
    meshrow: has_1["default"](),
    meta: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    metadata: has_1["default"](),
    meter: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    mpath: has_1["default"](),
    nav: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    noframes: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    noscript: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    object: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    ol: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    optgroup: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    option: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    output: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    p: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    param: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    path: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, PATH_SCHEMA),
    pattern: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    polygon: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, POLYGON_SCHEMA),
    polyline: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, POLYLINE_SCHEMA),
    pre: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    progress: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    q: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    radialGradient: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    rect: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA, RECT_SCHEMA),
    rp: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    rt: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    ruby: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    s: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    samp: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    script: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    section: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    select: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    set: has_1["default"](),
    small: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    solidcolor: has_1["default"](),
    source: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    span: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    stop: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    strike: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    strong: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    style: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    sub: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    summary: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    sup: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    svg: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA, STYLE_SCHEMA),
    "switch": has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    symbol: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    table: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    tbody: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    td: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    text: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    textarea: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    textPath: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    tfoot: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    th: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    thead: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    time: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    title: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    tr: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    track: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    tref: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    tspan: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA, PRESENTATION_SCHEMA),
    tt: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    u: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, TEXT_CONTENT_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    ul: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    unknown: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA),
    us: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, PRESENTATION_SCHEMA),
    use: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_2D_SCHEMA),
    "var": has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    video: has_1["default"](HTML_STYLE_SHORTHAND_SCHEMA, CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA),
    view: has_1["default"](),
    vkern: has_1["default"](),
    wb: has_1["default"](CONTROL_FLOW_SCHEMA, LAYOUT_3D_SCHEMA, STYLE_SCHEMA)
};
//# sourceMappingURL=schema.js.map