module.exports = [
  '@haiku/player',
  '@haiku/sdk-client',
  '@haiku/sdk-inkstone',
  '@haiku/cli',
  'haiku-sdk-creator',
  'haiku-common',
  'haiku-ui-common',
  'haiku-formats',
  'haiku-state-object',
  'haiku-websockets',
  'haiku-testing',
  'haiku-bytecode',
  'haiku-serialization',
  'haiku-creator',
  'haiku-glass',
  'haiku-timeline',
  'haiku-plumbing'
]
