module.exports = [
  'haiku-player',
  'haiku-sdk-client',
  'haiku-sdk-creator',
  'haiku-sdk-inkstone',
  'haiku-common',
  'haiku-ui-common',
  'haiku-formats',
  'haiku-state-object',
  'haiku-websockets',
  'haiku-testing',
  'haiku-bytecode',
  'haiku-serialization',
  'haiku-cli',
  'haiku-creator',
  'haiku-glass',
  'haiku-timeline',
  'haiku-plumbing'
]
