/** This file was autogenerated by Haiku at 20170814202043. */
var HaikuDOMAdapter = require('./../../../../../../lib/adapters/dom')
module.exports = HaikuDOMAdapter(require('./code'), {
  loop: true
})
