declare let parseCssTransformString: any;
declare let visitManaTree: any;
declare let parseCssValue: any;
declare let ROOT_LOCATOR: string;
declare let TRANSFORM_COMPONENT_WHITELIST: {
    "rotation.x": boolean;
    "rotation.y": boolean;
    "rotation.z": boolean;
    "rotation.w": boolean;
    "scale.x": boolean;
    "scale.y": boolean;
    "scale.z": boolean;
    "translation.x": boolean;
    "translation.y": boolean;
    "translation.z": boolean;
    "mount.x": boolean;
    "mount.y": boolean;
    "mount.z": boolean;
    "origin.x": boolean;
    "origin.y": boolean;
    "origin.z": boolean;
    "align.x": boolean;
    "align.y": boolean;
    "align.z": boolean;
};
declare function determineSizingProp(sizeAxis: any, attributeValue: any): false | {
    name: string;
    value: any;
    mode: number;
};
