declare let Curves: any;
declare let CENT: number;
declare let OBJECT: string;
declare let NUMBER: string;
declare let KEYFRAME_ZERO: number;
declare let KEYFRAME_MARGIN: number;
declare let STRING: string;
declare function percentOfTime(t0: any, t1: any, tnow: any): number;
declare function valueAtPercent(v0: any, v1: any, pc: any): any;
declare function valueAtTime(v0: any, v1: any, t0: any, t1: any, tnow: any): any;
declare function interpolateValue(v0: any, v1: any, t0: any, t1: any, tnow: any, curve: any): any;
declare function interpolate(now: any, curve: any, started: any, ends: any, origin: any, destination: any): any;
declare function ascendingSort(a: any, b: any): number;
declare function numberize(n: any): number;
declare function sortedKeyframes(keyframeGroup: any): any;
declare function getKeyframesList(keyframeGroup: any, nowValue: any): any[];
declare function calculateValue(keyframeGroup: any, nowValue: any): any;
declare function calculateValueAndReturnUndefinedIfNotWorthwhile(keyframeGroup: any, nowValue: any): any;
declare function getTransitionValue(currentKeyframe: any, currentTransition: any, nextKeyframe: any, nextTransition: any, nowValue: any): any;
