/** This file was autogenerated by Haiku at 20170716095407. */
var React = require('react') // Installed as a peer dependency of '@haiku/player'
var ReactDOM = require('react-dom') // Installed as a peer dependency of '@haiku/player'
var HaikuReactAdapter = require('@haiku/player/dom/react')
var React_SuperComplex = HaikuReactAdapter(require('./dom'))
if (React_SuperComplex.default) React_SuperComplex = React_SuperComplex.default
module.exports = React_SuperComplex