#!/usr/bin/env python2.7
import sys
from os import path
import json
import subprocess

is_branch_checkout = sys.argv[3]
if is_branch_checkout == '0':
  # This is a file checkout. Nothing to do!
  sys.exit(0)

current_branch = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD']).strip()
experiment_branch = current_branch if current_branch == 'release' else 'development'
with open(path.join('packages', 'haiku-common', 'config', 'experiments.json')) as experiments_file:
  experiments = json.load(experiments_file)

if sys.argv[1] != sys.argv[2]:
  print 'Syncing dependencies....'
  subprocess.call(['yarn', 'install'])

print 'NOTE: you are on a {} branch.'.format(experiment_branch)
print 'The following experiments are enabled:'
print '\n'.join([
  ' - {}'.format(experiment) for experiment in experiments if experiments[experiment].get(experiment_branch, False)
])
