#!/usr/bin/env python
import os
import subprocess
import sys

if os.environ.get('SKIP_HAIKU_HOOKS', '0') == '1':
    # We have been expliticly asked to do nothing.
    sys.exit(0)

print('Syncing dependencies....')
subprocess.call(['yarn', 'install'])
