/** This file was autogenerated by Haiku at 20170814202043. */
var React = require('react') // Installed as a peer dependency of '@haiku/core'
var ReactDOM = require('react-dom') // Installed as a peer dependency of '@haiku/core'
var HaikuReactAdapter = require('@haiku/core/dom/react')
var React_TestMicro = HaikuReactAdapter(require('./dom'))
if (React_TestMicro.default) React_TestMicro = React_TestMicro.default
module.exports = React_TestMicro
