/** This file was autogenerated by Haiku at 20170805112033. */
/** Copyright (c) 2017 taylor2. All rights reserved. */
module.exports = {
  metadata: {
    uuid: "HAIKU_SHARE_UUID",
    type: "haiku",
    name: "ShadowGoof",
    relpath: "code/main/code.js",
    core: "2.1.23",
    version: "0.0.2",
    organization: "taylor2",
    project: "ShadowGoof",
    branch: "master"
  },

  options: {},
  states: {},
  eventHandlers: {},
  timelines: {
    Default: {
      "haiku:8f1027580d5e": {
        "style.WebkitTapHighlightColor": { "0": { value: "rgba(0,0,0,0)" } },
        "style.position": { "0": { value: "relative" } },
        "style.overflowX": { "0": { value: "hidden" } },
        "style.overflowY": { "0": { value: "hidden" } },
        "sizeAbsolute.x": { "0": { value: 550 } },
        "sizeAbsolute.y": { "0": { value: 400 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeMode.y": { "0": { value: 1 } },
        "sizeMode.z": { "0": { value: 1 } }
      },
      "haiku:a7eb456f34e6": {
        viewBox: { "0": { value: "0 0 115 115" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 115 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 115 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 48, edited: true } },
        "translation.y": { "0": { value: 45.5, edited: true } },
        "style.zIndex": { "0": { value: 1 } }
      },
      "haiku:c52ae31b66f3": {
        cx: { "0": { value: "57.5" } },
        cy: { "0": { value: "55.5" } },
        r: { "0": { value: "53.5" } }
      },
      "haiku:176a54d8e9c3": {
        x: { "0": { value: "-6.5%" } },
        y: { "0": { value: "-4.7%" } },
        filterUnits: { "0": { value: "objectBoundingBox" } },
        "sizeProportional.x": { "0": { value: 1.131 } },
        "sizeMode.x": { "0": { value: 0 } },
        "sizeProportional.y": { "0": { value: 1.131 } },
        "sizeMode.y": { "0": { value: 0 } }
      },
      "haiku:fcb7a6962a2e": {
        dx: { "0": { value: "0" } },
        dy: { "0": { value: "2" } },
        in: { "0": { value: "SourceAlpha" } },
        result: { "0": { value: "shadowOffsetOuter1" } }
      },
      "haiku:db29f07d0e28": {
        stdDeviation: { "0": { value: "2" } },
        in: { "0": { value: "shadowOffsetOuter1" } },
        result: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:c55c53b7c842": {
        values: {
          "0": { value: "0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0" }
        },
        in: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:af599f33b4f1": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:704665cf4492": {
        fill: { "0": { value: "black" } },
        "fill-opacity": { "0": { value: "1" } },
        filter: { "0": { value: "url(#filter-2-853935)" } },
        "xlink:href": { "0": { value: "#path-1-853935" } }
      },
      "haiku:9275fc957ecb": {
        fill: { "0": { value: "#4AFEA9" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-853935" } }
      },
      "haiku:82a3c7c99c9e": {
        viewBox: { "0": { value: "0 0 138 138" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 138 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 138 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 162.5, edited: true } },
        "translation.y": { "0": { value: 190, edited: true } },
        "style.zIndex": { "0": { value: 2 } }
      },
      "haiku:d659688e2329": {
        cx: { "0": { value: "69" } },
        cy: { "0": { value: "66" } },
        r: { "0": { value: "46" } }
      },
      "haiku:34c6908c66d9": {
        x: { "0": { value: "-40.8%" } },
        y: { "0": { value: "-37.5%" } },
        filterUnits: { "0": { value: "objectBoundingBox" } },
        "sizeProportional.x": { "0": { value: 1.815 } },
        "sizeMode.x": { "0": { value: 0 } },
        "sizeProportional.y": { "0": { value: 1.815 } },
        "sizeMode.y": { "0": { value: 0 } }
      },
      "haiku:30f114defa20": {
        dx: { "0": { value: "0" } },
        dy: { "0": { value: "3" } },
        in: { "0": { value: "SourceAlpha" } },
        result: { "0": { value: "shadowOffsetOuter1" } }
      },
      "haiku:2d63b291f99a": {
        stdDeviation: { "0": { value: "12" } },
        in: { "0": { value: "shadowOffsetOuter1" } },
        result: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:2b6097358163": {
        values: {
          "0": { value: "0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0" }
        },
        in: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:829d98e73a34": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:6310c46c94cd": {
        fill: { "0": { value: "black" } },
        "fill-opacity": { "0": { value: "1" } },
        filter: { "0": { value: "url(#filter-2-3be63b)" } },
        "xlink:href": { "0": { value: "#path-1-3be63b" } }
      },
      "haiku:3411cfa258d6": {
        fill: { "0": { value: "#DB4AFE" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-3be63b" } }
      },
      "haiku:8975f7e2b471": {
        viewBox: { "0": { value: "0 0 100 128" } },
        "style.position": { "0": { value: "absolute" } },
        "style.margin": { "0": { value: "0" } },
        "style.padding": { "0": { value: "0" } },
        "style.border": { "0": { value: "0" } },
        "sizeAbsolute.x": { "0": { value: 100 } },
        "sizeMode.x": { "0": { value: 1 } },
        "sizeAbsolute.y": { "0": { value: 128 } },
        "sizeMode.y": { "0": { value: 1 } },
        "translation.x": { "0": { value: 333.5, edited: true } },
        "translation.y": { "0": { value: 45, edited: true } },
        "style.zIndex": { "0": { value: 3 } }
      },
      "haiku:767035af6bc1": {
        cx: { "0": { value: "50" } },
        cy: { "0": { value: "46" } },
        r: { "0": { value: "46" } }
      },
      "haiku:b1795703f5fc": {
        x: { "0": { value: "-23.9%" } },
        y: { "0": { value: "-19.6%" } },
        filterUnits: { "0": { value: "objectBoundingBox" } },
        "sizeProportional.x": { "0": { value: 1.4780000000000002 } },
        "sizeMode.x": { "0": { value: 0 } },
        "sizeProportional.y": { "0": { value: 1.7830000000000001 } },
        "sizeMode.y": { "0": { value: 0 } }
      },
      "haiku:51c260be6ef1": {
        dx: { "0": { value: "0" } },
        dy: { "0": { value: "32" } },
        in: { "0": { value: "SourceAlpha" } },
        result: { "0": { value: "shadowOffsetOuter1" } }
      },
      "haiku:d51cb3f86cb0": {
        stdDeviation: { "0": { value: "2" } },
        in: { "0": { value: "shadowOffsetOuter1" } },
        result: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:394be706480a": {
        values: {
          "0": { value: "0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0" }
        },
        in: { "0": { value: "shadowBlurOuter1" } }
      },
      "haiku:b2b56ee8eb21": {
        stroke: { "0": { value: "none" } },
        "stroke-width": { "0": { value: "1" } },
        fill: { "0": { value: "none" } },
        "fill-rule": { "0": { value: "evenodd" } }
      },
      "haiku:44babfc22325": {
        fill: { "0": { value: "black" } },
        "fill-opacity": { "0": { value: "1" } },
        filter: { "0": { value: "url(#filter-2-9ad209)" } },
        "xlink:href": { "0": { value: "#path-1-9ad209" } }
      },
      "haiku:40dbd1fb24fd": {
        fill: { "0": { value: "#FE4A4A" } },
        "fill-rule": { "0": { value: "evenodd" } },
        "xlink:href": { "0": { value: "#path-1-9ad209" } }
      }
    }
  },

  template: {
    elementName: "div",
    attributes: { "haiku-title": "ShadowGoof", "haiku-id": "8f1027580d5e" },
    children: [
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/Oval.svg",
          "haiku-title": "Oval",
          "haiku-id": "a7eb456f34e6"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "0b3e931b1c0a" },
            children: ["Oval"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "46fa53fada5d" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "db32c7a50dca" },
            children: [
              {
                elementName: "circle",
                attributes: { id: "path-1-853935", "haiku-id": "c52ae31b66f3" },
                children: []
              },
              {
                elementName: "filter",
                attributes: {
                  id: "filter-2-853935",
                  "haiku-id": "176a54d8e9c3",
                  "sizeMode.x": 0,
                  "sizeMode.y": 0
                },
                children: [
                  {
                    elementName: "feOffset",
                    attributes: { "haiku-id": "fcb7a6962a2e" },
                    children: []
                  },
                  {
                    elementName: "feGaussianBlur",
                    attributes: { "haiku-id": "db29f07d0e28" },
                    children: []
                  },
                  {
                    elementName: "feColorMatrix",
                    attributes: { type: "matrix", "haiku-id": "c55c53b7c842" },
                    children: []
                  }
                ]
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "af599f33b4f1" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Oval", "haiku-id": "fd3d1cb944eb" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "704665cf4492" },
                    children: []
                  },
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "9275fc957ecb" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/Oval Copy.svg",
          "haiku-title": "Oval Copy",
          "haiku-id": "82a3c7c99c9e"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "f762bf7e854e" },
            children: ["Oval Copy"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "85d8b50784cf" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "8dfd4349f5ab" },
            children: [
              {
                elementName: "circle",
                attributes: { id: "path-1-3be63b", "haiku-id": "d659688e2329" },
                children: []
              },
              {
                elementName: "filter",
                attributes: {
                  id: "filter-2-3be63b",
                  "haiku-id": "34c6908c66d9",
                  "sizeMode.x": 0,
                  "sizeMode.y": 0
                },
                children: [
                  {
                    elementName: "feOffset",
                    attributes: { "haiku-id": "30f114defa20" },
                    children: []
                  },
                  {
                    elementName: "feGaussianBlur",
                    attributes: { "haiku-id": "2d63b291f99a" },
                    children: []
                  },
                  {
                    elementName: "feColorMatrix",
                    attributes: { type: "matrix", "haiku-id": "2b6097358163" },
                    children: []
                  }
                ]
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "829d98e73a34" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Oval-Copy", "haiku-id": "6092ad310a5f" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "6310c46c94cd" },
                    children: []
                  },
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "3411cfa258d6" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        elementName: "svg",
        attributes: {
          version: "1.1",
          xmlns: "http://www.w3.org/2000/svg",
          "xmlns:xlink": "http://www.w3.org/1999/xlink",
          source: "designs/fauxshaux.sketch.contents/slices/Oval Copy 2.svg",
          "haiku-title": "Oval Copy 2",
          "haiku-id": "8975f7e2b471"
        },
        children: [
          {
            elementName: "title",
            attributes: { "haiku-id": "d688012b6f1e" },
            children: ["Oval Copy 2"]
          },
          {
            elementName: "desc",
            attributes: { "haiku-id": "9a2d3d6ae415" },
            children: ["Created with sketchtool."]
          },
          {
            elementName: "defs",
            attributes: { "haiku-id": "296b76c7f533" },
            children: [
              {
                elementName: "circle",
                attributes: { id: "path-1-9ad209", "haiku-id": "767035af6bc1" },
                children: []
              },
              {
                elementName: "filter",
                attributes: {
                  id: "filter-2-9ad209",
                  "haiku-id": "b1795703f5fc",
                  "sizeMode.x": 0,
                  "sizeMode.y": 0
                },
                children: [
                  {
                    elementName: "feOffset",
                    attributes: { "haiku-id": "51c260be6ef1" },
                    children: []
                  },
                  {
                    elementName: "feGaussianBlur",
                    attributes: { "haiku-id": "d51cb3f86cb0" },
                    children: []
                  },
                  {
                    elementName: "feColorMatrix",
                    attributes: { type: "matrix", "haiku-id": "394be706480a" },
                    children: []
                  }
                ]
              }
            ]
          },
          {
            elementName: "g",
            attributes: { id: "Page-1", "haiku-id": "b2b56ee8eb21" },
            children: [
              {
                elementName: "g",
                attributes: { id: "Oval-Copy-2", "haiku-id": "f3a72d87ea92" },
                children: [
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "44babfc22325" },
                    children: []
                  },
                  {
                    elementName: "use",
                    attributes: { "haiku-id": "40dbd1fb24fd" },
                    children: []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
};
