declare let assignStyle: any;
declare let assignClass: any;
declare let assignEvent: any;
declare let getFlexId: any;
declare let STYLE: string;
declare let OBJECT: string;
declare let FUNCTION: string;
declare let CLASS: string;
declare let CLASS_NAME: string;
declare let XLINK_XMLNS: string;
declare let X: string;
declare let L: string;
declare let I: string;
declare let N: string;
declare let K: string;
declare let D: string;
declare let A: string;
declare let T: string;
declare let COLON: string;
declare let M: string;
declare let G: string;
declare let E: string;
declare let FSLASH: string;
declare function setAttribute(el: any, key: any, val: any, component: any, cache: any): void;
declare function assignAttributes(domElement: any, virtualElement: any, component: any, isPatchOperation: any, isKeyDifferent: any): any;
