/** This file was autogenerated by Haiku at 20170822094748. */
var HaikuDOMAdapter = require('./../../../../../../src/adapters/dom')
module.exports = HaikuDOMAdapter(require('./code'), {
  loop: true
})