/** This file was autogenerated by Haiku at 20170822094748. */
var React = require('react') // Installed as a peer dependency of '@haiku/player'
var ReactDOM = require('react-dom') // Installed as a peer dependency of '@haiku/player'
var HaikuReactAdapter = require('@haiku/player/dom/react')
var React_simpSectTwo = HaikuReactAdapter(require('./dom'))
if (React_simpSectTwo.default) React_simpSectTwo = React_simpSectTwo.default
module.exports = React_simpSectTwo