/** This file was autogenerated by Haiku at 20170822092306. */
var React = require('react') // Installed as a peer dependency of '@haiku/player'
var ReactDOM = require('react-dom') // Installed as a peer dependency of '@haiku/player'
var HaikuReactAdapter = require('./../../../../../../lib/adapters/react-dom')
var React_particle = HaikuReactAdapter(require('./dom'))
if (React_particle.default) React_particle = React_particle.default
module.exports = React_particle