declare let matchById: any;
declare let matchByClass: any;
declare let matchByTagName: any;
declare let matchByAttribute: any;
declare let matchByHaiku: any;
declare let attrSelectorParser: any;
declare let ID_PREFIX: string;
declare let CLASS_PREFIX: string;
declare let ATTR_PREFIX: string;
declare let HAIKU_PREFIX: string;
declare function matchOne(node: any, piece: any, options: any): boolean;
